
import * as RNModule from 'react-native';

const RN = (RNModule as any).default || RNModule;

export const {
    AccessibilityInfo,
    ActivityIndicator,
    Button,
    DatePickerIOS,
    DrawerLayoutAndroid,
    FlatList,
    Image,
    ImageBackground,
    InputAccessoryView,
    KeyboardAvoidingView,
    ListView,
    Modal,
    Picker,
    PickerIOS,
    ProgressBarAndroid,
    ProgressViewIOS,
    RefreshControl,
    SafeAreaView,
    ScrollView,
    SectionList,
    SegmentedControlIOS,
    Slider,
    StatusBar,
    Switch,
    TabBarIOS,
    Text,
    TextInput,
    Touchable,
    TouchableHighlight,
    TouchableNativeFeedback,
    TouchableOpacity,
    TouchableWithoutFeedback,
    View,
    VirtualizedList,
    VirtualizedSectionList,
    ActionSheetIOS,
    Alert,
    AlertIOS,
    Animated,
    AppRegistry,
    AppState,
    AsyncStorage,
    BackAndroid,
    BackHandler,
    CameraRoll,
    Clipboard,
    DatePickerAndroid,
    DeviceEventEmitter,
    Dimensions,
    Easing,
    ImageEditor,
    ImagePickerIOS,
    ImageStore,
    InteractionManager,
    Keyboard,
    LayoutAnimation,
    Linking,
    NativeEventEmitter,
    NativeModules,
    NetInfo,
    PanResponder,
    PermissionsAndroid,
    PixelRatio,
    Platform,
    PushNotificationIOS,
    Settings,
    Share,
    StatusBarIOS,
    StyleSheet,
    Systrace,
    TimePickerAndroid,
    ToastAndroid,
    Vibration,
    VibrationIOS,
    YellowBox,
} = RN;

// Export strict types if needed or other specific things manually
export type {
    ViewStyle,
    TextStyle,
    ImageStyle,
    StyleProp,
    ViewProps,
    TextProps,
    ImageProps,
    ScrollViewProps,
    FlatListProps,
    TouchableOpacityProps,
} from 'react-native';

export default RN;
