
import * as RN from 'react-native';

export const {
    AccessibilityInfo,
    ActivityIndicator,
    Button,
    FlatList,
    Image,
    ImageBackground,
    KeyboardAvoidingView,
    Modal,
    RefreshControl,
    SafeAreaView,
    ScrollView,
    SectionList,
    StatusBar,
    Switch,
    Text,
    TextInput,
    TouchableHighlight,
    TouchableOpacity,
    TouchableWithoutFeedback,
    View,
    VirtualizedList,
    Alert,
    Animated,
    AppRegistry,
    AppState,
    BackHandler,
    DeviceEventEmitter,
    Dimensions,
    Easing,
    InteractionManager,
    Keyboard,
    LayoutAnimation,
    Linking,
    NativeEventEmitter,
    NativeModules,
    PanResponder,
    PixelRatio,
    Platform,
    Settings,
    Share,
    StyleSheet,
    Vibration,
} = RN;

// Export strict types
export type {
    ViewStyle,
    TextStyle,
    ImageStyle,
    StyleProp,
    ViewProps,
    TextProps,
    ImageProps,
    ScrollViewProps,
    FlatListProps,
    TouchableOpacityProps,
} from 'react-native';

export default RN;
